### ISSUE TITLE
Failed to build on Slackware/gcc/g++ 4.8.2

### ISSUE THREAD

**Issue by bdheeman** [agl/jbig2enc#54]
I attempted to build and package it for Slackware (Porteus, indeed), but it failed using gcc/g++ version 4.8.2; though I locally and successfully build the following dependencies:

_openjpeg 2.1.2
libwebp 0.6.0
libtiff 3.9.7
libpng 1.4.12
libjpeg v8a
leptonica 1.74.4_

```
jbig2.cc: In function ‘PIX* segment_image(PIX*, PIX*)’:
jbig2.cc:137:71: error: ‘expandBinaryPower2Low’ was not declared in this scope
                         pixd4->data, pixd4->w, pixd4->h, pixd4->wpl, 4);
                                                                       ^
```
**I'm not a programmer, hence I followed INSTALL/README for all the above, but the jbig2enc lacks this kind of requisite and important information :-(**

**Comment by bdheeman** [comment]
The **git version/master I cloned today build nicely with above libraries**, hence it can use a latest release of _leptonica 1.74.4_, as well and worked well for creating high quality PDF files from scanned black and white or monochrome 1-bit PBM files.

**Thank you, and thank you for making available such a wonderful tool publicly.**
