### ISSUE TITLE
error: use of undeclared identifier 'expandBinaryPower2Low'

### ISSUE THREAD

**Issue by ryandesign** [agl/jbig2enc#45]
jbig2enc 0.28 does not build with leptonica 1.70:

```
jbig2.cc:136:3: error: use of undeclared identifier 'expandBinaryPower2Low'
  expandBinaryPower2Low(pixd->data, pixd->w, pixd->h, pixd->wpl,
  ^
1 error generated.
```

This was reported to the MacPorts project here: https://trac.macports.org/ticket/43185
