### ISSUE TITLE
jbig2enc does not compile with Leptonica 1.68

### ISSUE THREAD

**Issue by mistydemeo** [agl/jbig2enc#12]
I'm unable to get jbig2enc to compile under Mac OS X, using either 0.27 or the latest source from git. I get the following error message for jbig2.cc:

g++ -o jbig2 jbig2.cc -L. -ljbig2enc `brew --prefix`/lib/liblept.a -I`brew --prefix`/include/leptonica/ -Wall -I`brew --prefix`/include -L`brew --prefix`/lib -O3  -lpng -ljpeg -ltiff -lm
jbig2.cc: In function ‘int main(int, char*_)’:
jbig2.cc:349: error: cannot convert ‘FILE_’ to ‘const char_’ for argument ‘1’ to ‘l_int32 findFileFormat(const char_, l_int32_)’
make: *_\* [jbig2] Error 1
